services:
  db:
    image: postgres:14.10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - fa_postgres_data:/var/lib/postgresql/data

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./api/data:/app/data
    command: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    depends_on:
      - spark
    ports:
      - "8081:8081"
    volumes:
      - ./api/data:/app/data
    command: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark:7077"]
    
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - spark
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./api:/app
    
volumes:
  fa_postgres_data:
